function salvarSysParametros() {var data = {} 
data["cmd"] =''; 
data["id_param"] =  $("#id_param").autoNumeric('get'); 
data["id_usuario_admin"] =  $("#id_usuario_admin").autoNumeric('get'); 
data["flag_manutencao"] =  $("#flag_manutencao").val(); 
data["desc_key"] =  $("#desc_key").val(); 
data["segs_teste_ajax"] =  $("#segs_teste_ajax").autoNumeric('get'); 
data["face_app_id"] =  $("#face_app_id").autoNumeric('get'); 
data["face_app_secretkey"] =  $("#face_app_secretkey").val(); 
data["face_app_token"] =  $("#face_app_token").val(); 
data["face_redirect_uri"] =  $("#face_redirect_uri").val(); 
data["url_system"] =  $("#url_system").val(); 
data["sys_host_name_smtp"] =  $("#sys_host_name_smtp").val(); 
data["sys_smtp_port"] =  $("#sys_smtp_port").autoNumeric('get'); 
data["sys_email"] =  $("#sys_email").val(); 
data["sys_senha"] =  $("#sys_senha").val(); 
data["sys_fromemail"] =  $("#sys_fromemail").val(); 
data["sys_fromdesc"] =  $("#sys_fromdesc").val(); 
data["sys_tls"] =  $("#sys_tls").val(); 
data["id_visitante"] =  $("#id_visitante").autoNumeric('get'); 
data["ped_horasokey"] =  $("#ped_horasokey").autoNumeric('get'); 
data["num_tempomaxcanc_minuto"] =  $("#num_tempomaxcanc_minuto").autoNumeric('get'); 
data["cod_recusa"] =  $("#cod_recusa").autoNumeric('get'); 
data["onesignal_key"] =  $("#onesignal_key").val(); 
data["onesignal_url"] =  $("#onesignal_url").val(); 
data["onesignal_appid"] =  $("#onesignal_appid").val(); 
data["num_minutos_not_final"] =  $("#num_minutos_not_final").autoNumeric('get'); 
data["num_segs_not_final_exec"] =  $("#num_segs_not_final_exec").autoNumeric('get'); 
data["cod_cancelamentosys"] =  $("#cod_cancelamentosys").autoNumeric('get'); 
data["desc_webappfolder"] =  $("#desc_webappfolder").val(); 
data["ignorar_regramaior18"] =  $("#ignorar_regramaior18").val(); 
data["face_redirect_uri_webapp"] =  $("#face_redirect_uri_webapp").val(); 
data["tragoaqui_num_telefone"] =  $("#tragoaqui_num_telefone").val(); 
data["tragoaqui_pag_facebook"] =  $("#tragoaqui_pag_facebook").val(); 
data["app_versao"] =  $("#app_versao").val(); 
data["applicacao"] =  $("#applicacao").autoNumeric('get'); 
data["sys_minutes_agen_not_resp"] =  $("#sys_minutes_agen_not_resp").autoNumeric('get'); 
data["url_websocket"] =  $("#url_websocket").val(); 
$.blockUI({message : 'Salvando...'});$.ajax({type : "POST",	url : "?acao=ajax",	dataType : "json",async : true,	data : data,	success : function(data) {if (data.msgok == 'ok') { sysMsg(data.msg,'M'); setTimeout(function() { $.unblockUI();}, 3000);} else {$.unblockUI();sysMsg(data.erro, 'E');}	$.unblockUI();}, error : function(msg) {$.unblockUI();}});}	$(document).ready(function() {	$("#btn_salvar").click(function() { salvarsys_parametros(); }); $("#id_param").autoNumeric('init',inteiro); 
 $("#id_usuario_admin").autoNumeric('init',inteiro); 
 $("#segs_teste_ajax").autoNumeric('init',inteiro); 
 $("#face_app_id").autoNumeric('init',inteiro); 
 $("#sys_smtp_port").autoNumeric('init',inteiro); 
 $("#id_visitante").autoNumeric('init',inteiro); 
 $("#ped_horasokey").autoNumeric('init',inteiro); 
 $("#num_tempomaxcanc_minuto").autoNumeric('init',inteiro); 
 $("#cod_recusa").autoNumeric('init',inteiro); 
 $("#num_minutos_not_final").autoNumeric('init',inteiro); 
 $("#num_segs_not_final_exec").autoNumeric('init',inteiro); 
 $("#cod_cancelamentosys").autoNumeric('init',inteiro); 
 $("#applicacao").autoNumeric('init',inteiro); 
 $("#sys_minutes_agen_not_resp").autoNumeric('init',inteiro); 
});function listaSysParametros() {var data = {} 
data["cmd"] =''; 
data["id_param"] =  $("#id_param").autoNumeric('get'); 
$.blockUI({message : 'Carregando...'});$.ajax({type : "POST",	url : "?acao=ajax",	dataType : "json",async : true,	data : data,	success : function(data) {if (data.msgok == 'ok') { $("#id_param").autoNumeric('set',data.id_param); 
 $("#id_usuario_admin").autoNumeric('set',data.id_usuario_admin); 
$("#flag_manutencao").val(data.flag_manutencao); 
$("#desc_key").val(data.desc_key); 
 $("#segs_teste_ajax").autoNumeric('set',data.segs_teste_ajax); 
 $("#face_app_id").autoNumeric('set',data.face_app_id); 
$("#face_app_secretkey").val(data.face_app_secretkey); 
$("#face_app_token").val(data.face_app_token); 
$("#face_redirect_uri").val(data.face_redirect_uri); 
$("#url_system").val(data.url_system); 
$("#sys_host_name_smtp").val(data.sys_host_name_smtp); 
 $("#sys_smtp_port").autoNumeric('set',data.sys_smtp_port); 
$("#sys_email").val(data.sys_email); 
$("#sys_senha").val(data.sys_senha); 
$("#sys_fromemail").val(data.sys_fromemail); 
$("#sys_fromdesc").val(data.sys_fromdesc); 
$("#sys_tls").val(data.sys_tls); 
 $("#id_visitante").autoNumeric('set',data.id_visitante); 
 $("#ped_horasokey").autoNumeric('set',data.ped_horasokey); 
 $("#num_tempomaxcanc_minuto").autoNumeric('set',data.num_tempomaxcanc_minuto); 
 $("#cod_recusa").autoNumeric('set',data.cod_recusa); 
$("#onesignal_key").val(data.onesignal_key); 
$("#onesignal_url").val(data.onesignal_url); 
$("#onesignal_appid").val(data.onesignal_appid); 
 $("#num_minutos_not_final").autoNumeric('set',data.num_minutos_not_final); 
 $("#num_segs_not_final_exec").autoNumeric('set',data.num_segs_not_final_exec); 
 $("#cod_cancelamentosys").autoNumeric('set',data.cod_cancelamentosys); 
$("#desc_webappfolder").val(data.desc_webappfolder); 
$("#ignorar_regramaior18").val(data.ignorar_regramaior18); 
$("#face_redirect_uri_webapp").val(data.face_redirect_uri_webapp); 
$("#tragoaqui_num_telefone").val(data.tragoaqui_num_telefone); 
$("#tragoaqui_pag_facebook").val(data.tragoaqui_pag_facebook); 
$("#app_versao").val(data.app_versao); 
 $("#applicacao").autoNumeric('set',data.applicacao); 
 $("#sys_minutes_agen_not_resp").autoNumeric('set',data.sys_minutes_agen_not_resp); 
$("#url_websocket").val(data.url_websocket); 
} else {$.unblockUI();sysMsg(data.erro, 'E');}	$.unblockUI();}, error : function(msg) {$.unblockUI();}});}